version: "3.9"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/code:cached
    command: sleep infinity
    working_dir: /code
    env_file:
      - ../.env
    networks:
      - dev_net
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev_net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - dev_net

networks:
  dev_net:

volumes:
  pgdata:
